apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/tunestack-503619/secrets/grafana-admin-password/versions/latest"
        path: "grafana-admin-password"
