apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-secrets-ksa
  namespace: monitoring
  annotations:
    iam.gke.io/gcp-service-account: grafana-secrets-sa@tunestack-503619.iam.gserviceaccount.com
